### ISSUE TITLE
Can you please make it compatible with FSRS4Anki ?

### ISSUE THREAD

**Issue by lucatortiglione** [tvhong/incremental-reading#23]
Please, make it compatible with that awesome addon
https://github.com/open-spaced-repetition/fsrs4anki

**Comment by tvhong** [comment]
Hi,
Could you please provide issue reproduction steps?

**Comment by lucatortiglione** [comment]
> Hi, Could you please provide issue reproduction steps?

Hi!
i just wanted to get you aware of the fact the addon isn't compatible.
I'm not able to use your addon yet.
I think you could contact fsrs author and ask him

**Comment by IshiRenga** [comment]
I'm not sure why OP didn't provide you with the required details to understand the issue entirely, but allow me to do that as I have also run into this bug. The OP is referring to an incompatibility with the custom scheduling feature in Anki's V3 scheduler (FSRS is one such custom scheduler). When the incremental reading add-on is enabled, the custom scheduler doesn't seem to work. By that I mean that the intervals given to a card are from Anki's default algorithm instead of the custom one. I believe to solve this issue would mean fixing this incompatibility.

**Comment by tvhong** [comment]
@IshiRenga thank you for providing the details.

Is this happening when you have a deck with a mix of both IR3 (Incremental Reading) cards and normal cards? Or also happen for decks with purely normal cards?

Do you have easy reproduction steps (+ expected outcome)? I'm not very familiar with how interval settings differ between the default Anki vs. FSRS work.

**Comment by tvhong** [comment]
I also just saw that FSRS is being integrated into Anki 23.10
> FSRS has been integrated into Anki. If your version of Anki is 23.10 or newer, use the built-in FSRS. Read about how to use it [here](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/README2.md). If your version of Anki is 2.1.66 or older, use the standalone version.

Would be interesting to see whether this bug just automatically go away when that happens.

**Comment by tvhong** [comment]
Thanks for sharing the link!

Another user already reported compatibility issue with Qt5 that I already fixed: https://github.com/tvhong/incremental-reading/issues/28

I see that IR uses `note.flush()`. So I'll make a small fix for that as well.

**Comment by tvhong** [comment]
Another user also report FSRS issues on Anki forum: https://forums.ankiweb.net/t/incremental-reading-add-on-unofficial-clone/21331/15

They also suggested a fix. I'll try to reproduce and evaluate the fix.
